<?php

namespace Database\Seeders;

use App\Helpers\STATUS;
use App\Models\Department;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DepartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $department = [
            ['name' => 'Cardiology', 'description' => "Orthopedics stands as a stalwart medical specialty, dedicated to unraveling the complexities of the musculoskeletal system. This intricate network of bones, joints, muscles, ligaments, tendons, and nerves forms the foundation of human movement and stability. Within this domain, orthopedic surgeons wield their expertise, navigating a diverse landscape of disorders and injuries. From the common fractures and arthritis to the more intricate spinal deformities and congenital anomalies, they stand as custodians of mobility and function. Employing a versatile arsenal of treatments ranging from surgical interventions to rehabilitative therapies, each patient's journey is a testament to the precision and compassion inherent in orthopedic care. The overarching goal remains unwavering: to restore mobility, alleviate pain, and foster a renewed quality of life amidst the challenges posed by musculoskeletal ailments.", 'photo' => '1.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Orthopedics', 'description' => "Orthopedics is a medical specialty that focuses on the diagnosis, treatment, and prevention of disorders and injuries affecting the musculoskeletal system. This system includes bones, joints, muscles, ligaments, tendons, and nerves. Orthopedic surgeons are trained to address a wide range of conditions, such as fractures, arthritis, sports injuries, spinal deformities, and congenital disorders. They employ various treatment modalities, including surgical interventions, medications, physical therapy, and rehabilitative techniques, tailored to each patient's unique needs. The goal of orthopedic care is to restore mobility, alleviate pain, and improve the overall function and quality of life for individuals with musculoskeletal issues.", 'photo' => '2.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Neurology', 'description' => "Neurology stands at the forefront of understanding and addressing the complexities of the human nervous system. This intricate network of the brain, spinal cord, and peripheral nerves governs every aspect of our existence, from sensation and movement to cognition and emotion. Within the realm of neurology, specialists delve deep into the mysteries of neurological disorders, ranging from common ailments like headaches and seizures to more profound conditions such as stroke, multiple sclerosis, and Parkinson's disease. Armed with advanced diagnostic tools like MRI, CT scans, and electroencephalography (EEG), neurologists unravel the intricacies of the brain's inner workings, striving to pinpoint the root causes of dysfunction. Treatment strategies span a spectrum, encompassing medications, rehabilitative therapies, and in some cases, intricate surgical interventions. Yet, beyond the realm of treatments, lies a profound commitment to compassion and understanding, as neurologists walk alongside their patients, navigating the complexities of neurological conditions and striving to improve their quality of life. In essence, neurology epitomizes the relentless pursuit of understanding and healing within the vast expanse of the human mind and nervous system.", 'photo' => '3.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Pediatrics', 'description' => "Pediatrics embodies the profound dedication to the health and well-being of our youngest patients, navigating the intricate journey from infancy to adolescence. As guardians of childhood, pediatricians embrace a holistic approach, addressing not only the physical but also the emotional and developmental needs of children. From routine check-ups and vaccinations to the management of acute illnesses and chronic conditions, pediatricians stand as pillars of support for both children and their families. With a keen eye for growth and development milestones, pediatricians foster a nurturing environment that promotes optimal health and thriving. Beyond the examination room, they serve as educators, empowering parents with the knowledge and tools needed to raise happy and healthy children. Every interaction is imbued with empathy and compassion, as pediatricians strive to create a safe and trusting space for children to flourish. In essence, pediatrics embodies the profound commitment to nurturing the next generation, shaping a brighter and healthier future for us all.", 'photo' => '4.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dermatology', 'description' => "Dermatology encapsulates the multifaceted realm of skin health, blending medical expertise with aesthetic care to address a diverse array of dermatological conditions. From common afflictions like acne and eczema to more complex disorders such as psoriasis and skin cancer, dermatologists employ advanced diagnostic techniques and treatment modalities to provide personalized care tailored to each patient's needs. Beyond medical interventions, dermatologists also offer cosmetic procedures to enhance the appearance and vitality of the skin, including laser therapy, chemical peels, and injectable fillers. With a steadfast commitment to both health and beauty, dermatologists strive to empower individuals to feel confident and comfortable in their skin, fostering a sense of well-being and self-assurance.", 'photo' => '5.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ophthalmology', 'description' => "Ophthalmology, the specialized field devoted to the intricate complexities of the eyes and vision, serves as a cornerstone of healthcare, safeguarding one of our most precious senses. Ophthalmologists are entrusted with the diagnosis, treatment, and prevention of a wide spectrum of ocular conditions, ranging from common refractive errors like nearsightedness and farsightedness to sight-threatening diseases such as glaucoma, cataracts, and retinal disorders. Armed with cutting-edge diagnostic technologies and surgical innovations, they strive to preserve and restore vision, offering customized treatment plans tailored to each patient's unique needs. From routine eye examinations to delicate surgical procedures, ophthalmologists approach every interaction with compassion and precision, recognizing the profound impact that vision has on quality of life. Beyond clinical care, they are at the forefront of research and education, advancing our understanding of ocular health and training the next generation of eye care professionals. In essence, ophthalmology embodies a profound commitment to vision preservation, enabling individuals to see the world with clarity and vitality.", 'photo' => '6.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Geriatrics', 'description' => "Geriatrics, a vital and specialized branch of medicine, is dedicated to the care and well-being of older adults, addressing the unique medical, social, and psychological needs associated with aging. Geriatricians, with their expertise in the complexities of aging, provide comprehensive and holistic care to older individuals, focusing on promoting health, independence, and quality of life. They assess and manage a wide range of age-related conditions, including chronic diseases, cognitive impairment, functional decline, and polypharmacy, with a keen understanding of the interplay between physical, mental, and social factors. Through personalized care plans tailored to individual needs and preferences, geriatricians prioritize patient-centered care, emphasizing preventive strategies, symptom management, and advanced care planning. Beyond clinical interventions, they advocate for older adults' rights and dignity, promoting age-friendly environments and fostering a culture of respect and inclusion. In essence, geriatrics embodies a profound commitment to optimizing the health and well-being of older adults, ensuring they age with dignity, grace, and vitality.", 'photo' => '7.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Urology', 'description' => "Urology, a cornerstone of medical care, is dedicated to the diagnosis, treatment, and management of disorders related to the urinary tract and male reproductive system. Urologists are skilled practitioners who address a wide spectrum of conditions, ranging from common ailments like urinary tract infections and kidney stones to more complex issues such as prostate cancer, erectile dysfunction, and infertility. Armed with advanced diagnostic tools and surgical techniques, urologists provide personalized care tailored to each patient's needs, striving to optimize urinary function, alleviate symptoms, and improve quality of life. From minimally invasive procedures to complex surgeries, urologists offer a comprehensive range of treatment options, always prioritizing patient comfort and well-being. Beyond clinical practice, they are at the forefront of research and innovation, driving advancements in urological care and contributing to the collective understanding of urological diseases. In essence, urology embodies a steadfast commitment to urinary health and reproductive wellness, empowering individuals to lead fulfilling and healthy lives.", 'photo' => '8.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hematology', 'description' => "Hematology, a vital branch of medicine, is dedicated to the study, diagnosis, and treatment of disorders related to the blood and blood-forming tissues. Hematologists are specialized physicians who possess expertise in the intricate mechanisms governing blood cell production, clotting processes, and immune function. They diagnose and manage a diverse range of conditions, including anemia, leukemia, lymphoma, bleeding disorders, and thrombotic disorders, employing a wide array of diagnostic tests and therapeutic interventions. Armed with advanced laboratory techniques and molecular diagnostics, hematologists decipher the underlying causes of blood disorders and develop personalized treatment plans tailored to each patient's needs. From blood transfusions and chemotherapy to stem cell transplants and targeted therapies, hematologists offer comprehensive care with a focus on improving patient outcomes and quality of life. Beyond clinical practice, they contribute to research efforts aimed at advancing our understanding of hematological diseases and developing novel treatment strategies. In essence, hematology embodies a commitment to the preservation of blood health and the pursuit of excellence in patient care, research, and education.", 'photo' => '9.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ENT', 'description' => "Otolaryngology, commonly known as ENT (Ear, Nose, and Throat), is a specialized medical field dedicated to the diagnosis, treatment, and management of disorders related to the ears, nose, throat, head, and neck. Otolaryngologists, or ENT specialists, possess expertise in a wide range of conditions, from common ailments such as ear infections, sinusitis, and tonsillitis to more complex issues such as hearing loss, voice disorders, and head and neck cancers. Utilizing advanced diagnostic tools such as endoscopy, imaging studies, and audiometry, ENT specialists accurately diagnose the underlying causes of these conditions and develop tailored treatment plans to address them effectively. Treatment options may include medication, surgical interventions, rehabilitation, and counseling, all aimed at improving patient outcomes and quality of life. With a comprehensive understanding of the interconnectedness of the ear, nose, and throat, ENT specialists play a crucial role in restoring sensory functions, relieving discomfort, and enhancing overall well-being for their patients. In essence, otolaryngology encompasses a holistic approach to the care of the head and neck region, blending medical expertise with compassionate care to optimize patient health and function.", 'photo' => '10.png', 'status' => STATUS::ACTIVE, 'created_at' => now(), 'updated_at' => now()]
        ];
        Department::insert($department);
    }
}
